Repository codesquad-member-2020/sidedish-09, pull requests merged in 2020-04, with the labels that each got.

#7 [FE] 캐러셀 슬라이더 (library ver.) 완성
  FE/sidedish/.gitignore
  FE/sidedish/README.md
  FE/sidedish/package.json
  FE/sidedish/public/favicon.ico
  FE/sidedish/public/index.html
  FE/sidedish/public/manifest.json
  FE/sidedish/src/assets/mockData.js
  FE/sidedish/src/assets/next.svg
  FE/sidedish/src/assets/prev.svg
  FE/sidedish/src/components/App.jsx
  FE/sidedish/src/components/carouselLibR/Badge.jsx
  FE/sidedish/src/components/carouselLibR/Carousel.jsx
  FE/sidedish/src/components/carouselLibR/CarouselHeader.jsx
  FE/sidedish/src/components/carouselLibR/CarouselItem.jsx
  FE/sidedish/src/index.js
  FE/sidedish/src/style/Badge.js
  FE/sidedish/src/style/Buttons.css
  FE/sidedish/src/style/Carousel.js
  FE/sidedish/src/style/CarouselHeader.js
  FE/sidedish/src/style/CarouselItem.js
  FE/sidedish/src/style/GlobalStyle.js
  FE/sidedish/yarn.lock
Labels: FE

#10 [BE] 백엔드 API 서버 개발설정
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/readme.md
  BE/settings.gradle
  BE/src/main/java/com/sidedish/be/BeApplication.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/logback.xml
  BE/src/test/java/com/sidedish/be/BeApplicationTests.java
Labels: be

#11 [FE] HeaderComponent 추가 완료
  FE/sidedish/package.json
  FE/sidedish/public/data/mockData.json
  FE/sidedish/src/components/App.jsx
  FE/sidedish/src/components/header/Header.jsx
  FE/sidedish/src/components/header/LinkNav.jsx
  FE/sidedish/src/components/header/LogoNav.jsx
  FE/sidedish/src/components/header/MenuNav.jsx
  FE/sidedish/src/index.js
  FE/sidedish/src/style/GlobalStyle.js
  FE/sidedish/src/style/common.scss
  FE/sidedish/src/style/header/linkNav.js
  FE/sidedish/src/style/header/logoNav.js
  FE/sidedish/src/style/header/menuNav.js
  FE/sidedish/src/style/var.scss
  FE/sidedish/yarn.lock
Labels: FE

#17 React-alias 적용
  FE/sidedish/craco.config.js
  FE/sidedish/jsconfig.json
  FE/sidedish/jsconfig.paths.json
  FE/sidedish/package.json
  FE/sidedish/src/components/App.jsx
  FE/sidedish/src/components/carouselLibR/Badge.jsx
  FE/sidedish/src/components/carouselLibR/Carousel.jsx
  FE/sidedish/src/components/carouselLibR/CarouselHeader.jsx
  FE/sidedish/src/components/carouselLibR/CarouselItem.jsx
  FE/sidedish/src/components/header/LinkNav.jsx
  FE/sidedish/src/components/header/LogoNav.jsx
  FE/sidedish/src/components/header/MenuNav.jsx
  FE/sidedish/yarn.lock
Labels: FE

#20 craco 모듈 HotFix
  FE/sidedish/craco.config.js
  FE/sidedish/jsconfig.json
Labels: FE, Hot Fix

#21 [FE] 상세페이지 모달창 추가
  FE/sidedish/package.json
  FE/sidedish/src/assets/prodMockdata.js
  FE/sidedish/src/components/App.jsx
  FE/sidedish/src/components/carouselLibR/Badge.jsx
  FE/sidedish/src/components/carouselLibR/Carousel.jsx
  FE/sidedish/src/components/carouselLibR/CarouselHeader.jsx
  FE/sidedish/src/components/carouselLibR/CarouselItem.jsx
  FE/sidedish/src/components/product/Product.jsx
  FE/sidedish/src/components/product/ProductInfo.jsx
  FE/sidedish/src/components/product/ThumbnailViewer.jsx
  FE/sidedish/src/contexts/product.jsx
  FE/sidedish/src/style/carouselLibR/Badge.js
  FE/sidedish/src/style/carouselLibR/Buttons.css
  FE/sidedish/src/style/carouselLibR/Carousel.js
  FE/sidedish/src/style/carouselLibR/CarouselHeader.js
  FE/sidedish/src/style/carouselLibR/CarouselItem.js
  FE/sidedish/src/style/product/Product.js
  FE/sidedish/src/style/product/ProductInfo.js
  FE/sidedish/src/style/product/ThumbnailViewer.js
Labels: FE

#23 [FE] 상품상세 Toggle 기능 구현
  FE/sidedish/src/components/App.jsx
  FE/sidedish/src/components/carouselLibR/Carousel.jsx
  FE/sidedish/src/components/carouselLibR/CarouselItem.jsx
  FE/sidedish/src/components/product/Product.jsx
  FE/sidedish/src/contexts/product.jsx
  FE/sidedish/src/contexts/productContext.jsx
  FE/sidedish/src/hooks/useModal.jsx
Labels: FE

#27 [FE] Carousel Compoent (library ver.)
  FE/sidedish/.env.development
  FE/sidedish/src/components/App.jsx
  FE/sidedish/src/components/carouselLibH/Carousel.jsx
  FE/sidedish/src/style/carouselLibH/carousel.scss
  FE/sidedish/src/style/common.scss
Labels: FE

#31 [FE] 코드 리팩토링
  FE/sidedish/package.json
  FE/sidedish/src/components/carouselLibR/Carousel.jsx
  FE/sidedish/src/components/carouselLibR/CarouselHeader.jsx
  FE/sidedish/src/components/carouselLibR/CarouselItem.jsx
  FE/sidedish/src/components/product/ProductInfo.jsx
  FE/sidedish/src/components/product/ThumbnailViewer.jsx
  FE/sidedish/src/style/carouselLibR/Carousel.js
  FE/sidedish/src/style/carouselLibR/CarouselHeader.js
  FE/sidedish/src/style/carouselLibR/CarouselItem.js
  FE/sidedish/src/style/product/ProductInfo.js
Labels: FE

#37 상세 페이지 ModalComponent
  FE/sidedish/.env.development
  FE/sidedish/package.json
  FE/sidedish/src/components/App.jsx
  FE/sidedish/src/components/carouselLibH/Carousel.jsx
  FE/sidedish/src/components/carouselLibH/Detail.jsx
  FE/sidedish/src/components/carouselLibH/Main.jsx
  FE/sidedish/src/style/carouselLibH/detail.js
  FE/sidedish/src/style/carouselLibH/detailCarousel.scss
  FE/sidedish/yarn.lock
Labels: FE

#40 [FE] 서버 연동 완료
  FE/sidedish/.gitignore
  FE/sidedish/src/assets/mockData.js
  FE/sidedish/src/components/carouselLibR/Carousel.jsx
  FE/sidedish/src/components/carouselLibR/CarouselItem.jsx
  FE/sidedish/src/components/carouselLibR/const.js
  FE/sidedish/src/components/carouselLibR/product/Product.jsx
  FE/sidedish/src/components/carouselLibR/product/ProductInfo.jsx
  FE/sidedish/src/components/carouselLibR/product/ThumbnailViewer.jsx
  FE/sidedish/src/components/state/Loader.jsx
  FE/sidedish/src/components/state/Message.jsx
  FE/sidedish/src/contexts/productContext.jsx
  FE/sidedish/src/style/state/loader.js
  FE/sidedish/src/style/state/message.js
Labels: FE

#41 slider, 상세페이지 refactor
  FE/sidedish/.env.development
  FE/sidedish/package.json
  FE/sidedish/src/components/carouselLibH/Carousel.jsx
  FE/sidedish/src/components/carouselLibH/Detail.jsx
Labels: FE

#42 Carousel Loading Spinner 생성
  FE/sidedish/src/assets/loading.svg
  FE/sidedish/src/components/carouselLibH/Carousel.jsx
  FE/sidedish/src/components/carouselLibH/Detail.jsx
  FE/sidedish/src/style/carouselLibH/carousel.scss
  FE/sidedish/src/style/carouselLibH/detail.js
Labels: FE

#46 mockData axios로 요청하지 않고 임포트로 사용
  FE/sidedish/.env.development
  FE/sidedish/public/data/mockData.json
  FE/sidedish/src/assets/menuMockData.js
  FE/sidedish/src/components/header/MenuNav.jsx
Labels: FE

#50 [FE] 상품상세 버그 수정
  FE/sidedish/.env.development
  FE/sidedish/src/components/carouselLibR/product/ThumbnailViewer.jsx
  FE/sidedish/src/style/carouselLibR/Badge.js
Labels: Bug, FE
